clc;
clear;
close;

addpath('src');

% equation options
R0 = 50e-6;
Req = R0/10;
tfin = 15E-6;
kappa = 1.4;
Lheat = 2.378193575129533e+04;
T8 = 298.15;
rho8 = 1064;
tvector = linspace(0,tfin,100);
radial = 1;
vapor = 1;
bubtherm = 1;
medtherm = 1;
masstrans = 0;
stress = 2;
varin = {'progdisplay',0,...
    'radial',radial,...
         'bubtherm',bubtherm,...
         'tvector',tvector,...
         'vapor',vapor,...
         'medtherm',medtherm,...
         'method',23,...
         'stress',stress,...
         'collapse',1,...
         'mu',1E-4,...
         'g',2500,...
         'lambda1',1e-7,...
         'lambda2',0,...
         'alphax',1e-3,...
         'r0',R0,...
         'req',Req,...
         'kappa',kappa,...
         't8',T8,...
         'rho8',rho8};

[t1,R1,~] = m_imr_fd(varin{:},'Nt',70,'Mt',70);
[t2,R2,~] = m_imr_spectral(varin{:},'Nt',12,'Mt',12);

figure(1)
hold on;
plot(t1,R1,'bx')
plot(t2,R2,'g^')
ylim([0 1.2])