clc;
clear;
close;

addpath(genpath('src'));

% equation options
R0 = 100e-6;
Req = R0/10;
tfin = 1.5*R0; %160E-6;
kappa = 1.4;
Lheat = 2.378193575129533e+04;
T8 = 298.15;
rho8 = 998.2;
mu = 0;
Gelastic = 0;
tvector = linspace(0,tfin,500);
radial = 2;
vapor = 1;
collapse = 1;
bubtherm = 1;
medtherm = 1;
masstrans = 1;
stress = 1;
varin = {'progdisplay',0,...
         'radial',radial,...
         'bubtherm',bubtherm,...
         'tvector',tvector,...
         'vapor',vapor,...
         'medtherm',medtherm,...
         'masstrans',masstrans,...
         'method',23,...
         'stress',stress,...
         'collapse',collapse,...
         'mu',mu,...
         'g',Gelastic,...
         'lambda1',1e-7,...
         'lambda2',0,...
         'alphax',1e-3,...
         'r0',R0,...
         'req',Req,...
         'kappa',kappa,...
         't8',T8,...
         'rho8',rho8};

%[t1,R1,R1dot,P,T,Tm,kv] = m_imr_fd(varin{:},'Nt',100,'Mt',70);
[t1,R1,~] = m_imr_spectral(varin{:},'Nt',10,'Mt',10);

figure(1)
hold on;
plot(t1,R1,'b-');
ylim([0 1]);
